package com.jacob.apm.controllers;

/**
 * This class is generated by referring:
 * https://www.geeksforgeeks.org/spring-boot-3-0-jwt-authentication-with-spring-security-using-mysql-database/#
 */

import com.jacob.apm.constants.MainConstants;
import com.jacob.apm.models.AuthenticationRequest;
import com.jacob.apm.models.UserSignUpRequest;
import com.jacob.apm.services.APMUserService;
import com.jacob.apm.services.JwtService;
import com.jacob.apm.utilities.RecaptchaUtil;
import jakarta.servlet.http.Cookie;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/auth")
public class APMUserController {

    private static final Logger logger = LoggerFactory.getLogger(APMUserController.class.getName());

    @Autowired
    private APMUserService apmUserService;

    @Autowired
    private JwtService jwtService;

    @Autowired
    private AuthenticationManager authenticationManager;

    @PostMapping("/addNewUser")
    public ResponseEntity<?> addNewUser(@RequestBody UserSignUpRequest userSignUpRequest) {
        logger.info("Request received at /addNewUser. userSignUpRequest: " + userSignUpRequest.toLogString());

        String operationStatus = apmUserService.saveUserToDatabase(userSignUpRequest);

        if (operationStatus.equalsIgnoreCase(MainConstants.MSG_SUCCESS)) {
            return ResponseEntity.status(HttpStatus.ACCEPTED).body(MainConstants.MSG_SUCCESS);
        } else {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(operationStatus);
        }
    }

    @PostMapping("/generateToken")
    public ResponseEntity<?> authenticateAndGetToken(@RequestBody AuthenticationRequest authenticationRequest, HttpServletResponse response) {

        logger.info("Calling /generateToken. authenticationRequest: " + authenticationRequest.toLogString());
        if (authenticationRequest == null) {
            String errorMessage = "AuthenticationRequest object is null. ";
            logger.error(errorMessage);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(errorMessage);
        }

//        Validate Google reCaptcha.
        if(! (RecaptchaUtil.validateRecaptcha(authenticationRequest.getGoogleReCaptcha()))) {
            String errorMessage = "Google reCaptcha server-side verification failed. Client token: "+authenticationRequest.getGoogleReCaptcha();
            logger.error(errorMessage);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(errorMessage);
        }

        try {
            authenticationRequest.setUsername(authenticationRequest.getUsername().toLowerCase());
            Authentication authentication = authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(authenticationRequest.getUsername().toLowerCase(), authenticationRequest.getPassword()));
            if (authentication.isAuthenticated()) {
                String token = jwtService.generateToken(authenticationRequest.getUsername());

                // Set the token as an HTTP-only cookie
                Cookie cookieHttpOnly = new Cookie(MainConstants.COOKIE_HEADER_AUTHORIZATION, token);
                cookieHttpOnly.setHttpOnly(true);
                cookieHttpOnly.setPath("/");
                response.addCookie(cookieHttpOnly);

                Cookie cookieUsername = new Cookie(MainConstants.COOKIE_HEADER_PREFIX_USERNAME, authenticationRequest.getUsername());
                cookieUsername.setMaxAge(MainConstants.DURATION_MILLISECONDS_IN_ONE_HOUR);
                cookieUsername.setPath("/");
                response.addCookie(cookieUsername);

                String messageForLog = "Successfully generated JWT token and cookie for username: "+authenticationRequest.getUsername();
                logger.info(messageForLog);
                return ResponseEntity.status(HttpStatus.OK).body(MainConstants.MSG_SUCCESS);
            }
        }catch (Exception exception) {
            String messageForLog = "Could not create generate JWT token for username: "+authenticationRequest.getUsername();
            logger.error(messageForLog);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(exception);
        }

        String errorMessage = "Invalid credentials. " + authenticationRequest.toString();
        logger.error(errorMessage);
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(errorMessage);
    }

    @GetMapping("/logout")
    public ResponseEntity<?> logout(HttpServletRequest request, HttpServletResponse response) {

        logger.info("Calling /logout");
        try{
            Cookie[] cookies = request.getCookies();
            if (cookies != null) {
                for (Cookie cookie : cookies) {
                    cookie.setValue("");
                    cookie.setPath("/");
                    cookie.setMaxAge(0);
                    response.addCookie(cookie);
                }
            }
            logger.info("Cleared all cookies. Logout successful.");

        } catch (Exception exception) {
            logger.error("Failed to logout. " + exception.getMessage());
        }
        return ResponseEntity.status(HttpStatus.FOUND).header("Location", "/").body("");    }

    @PostMapping("/isUsernameAvailable")
    public ResponseEntity<?> isUsernameAvailable(@RequestBody UserSignUpRequest userSignUpRequest) {
        logger.info("Calling /isUsernameAvailable. userSignUpRequest: " + userSignUpRequest.toLogString());
        boolean operationStatus = apmUserService.isUsernameIsAvailable(userSignUpRequest);

        if (operationStatus == MainConstants.FLAG_SUCCESS) {
            return ResponseEntity.status(HttpStatus.OK).body(operationStatus);
        } else {
            return ResponseEntity.status(HttpStatus.CONFLICT).body(operationStatus);
        }
    }
}
